backend:
  name: git-gateway
  branch: main

media_folder: "/public/images/uploads"

collections:
  - name: "years" # Used in routes, e.g., /admin/collections/blog
    label: "rocniky" # Used in the UI
    folder: "src/years" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Rok", name: "year", widget: "number" }
      - { label: "Popis", name: "body", widget: "markdown" }
      - label: "Odkazy na výsledky"
        name: "vysledky"
        widget: "list"
        summary: "{{fields.label}}"
        fields:
          - { label: "Kategorie", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Galerie"
        name: "gallery"
        widget: "list"
        summary: "{{fields.image}}"
        fields:
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Odkaz na galerii", name: "link", widget: "string" }
      - { label: "Video ročníku", name: "video", widget: "string" }